---
title: "Flight Data Tutorial"
output: html_document
---

## R Markdown

```{r}
library(dplyr)
library(ggplot2)
library(gdata)
library(lubridate)
library(broom)
library(ROCR)
library(caret)
```


```{r}

flight_data <- read.csv("2004.csv.bz2")
```

```{r}
flight_data_jan <- flight_data %>% 
  filter(Month == 1) 
  
```

```{r}
flight_data_test <- read.xls ("FlightDelays.xls", sheet = 1, header = TRUE)
```

```{r}
#dont need this for the Flightdelays.xls sheet

#flight_data_test <- flight_data_test %>%
  #mutate(is_delayed = if_else(ArrDelay > 0, 1, 0))
  
  
```




```{r}
g <- ggplot(flight_data_test, aes(Flight.Status, fill= Flight.Status)) +
  geom_bar() +
  xlab("Flight Status") +
  ylab("Number of Flights")

g
```


```{r}
summary(flight_data_test$Flight.Status)
```

```{r}
summary(flight_data_test$CARRIER)
```

```{r}
#Plot out percentage of delays by airline
flight_data_test %>%
  group_by(CARRIER)%>%
  summarise( n = n()) %>%
  mutate(freq = round(n / sum(n), 2))
```



```{r}

#Plot out percentage of delays by day of week
day_of_week <- flight_data_test %>%
  group_by(DAY_WEEK, Flight.Status)%>%
  summarise( n = n()) %>%
  mutate(freq = n / sum(n))
  
day_of_week$Flight.Status <- relevel(day_of_week$Flight.Status, 'ontime')



ggplot(data= day_of_week, aes(x=DAY_WEEK, y=freq, fill=Flight.Status)) +
  geom_bar(stat="identity")
```

```{r}

#Plot out percentage of delays by airport destination

destination_airport <- flight_data_test %>%
  group_by(DEST, Flight.Status)%>%
  summarise( n = n()) %>%
  mutate(freq = n / sum(n))

destination_airport$Flight.Status <- relevel(destination_airport$Flight.Status, 'ontime')

ggplot(data= destination_airport, aes(x=DEST, y=freq, fill=Flight.Status)) +
  geom_bar(stat="identity")
```




```{r}

#Plot out percentage of delays by airport origin

origin_airport <- flight_data_test %>%
  group_by(ORIGIN, Flight.Status)%>%
  summarise( n = n()) %>%
  mutate(freq = n / sum(n))



origin_airport$Flight.Status <- relevel(origin_airport$Flight.Status, 'ontime')

ggplot(data= origin_airport
       
       , aes(x=ORIGIN, y=freq, fill=Flight.Status)) +
  geom_bar(stat="identity")
```

-----

#make dummy variables of categorical data

```{r}
flight_data_test$DAY_WEEK <- as.factor(flight_data_test$DAY_WEEK)
flights.dummy <- model.matrix(~CARRIER+DEST+ORIGIN+DAY_WEEK,data=flight_data_test)
flights.dummy <- flights.dummy[,-1]
```


#group by each hour

```{r}

flight_data_test$hour <- floor(flight_data_test$DEP_TIME/100)

flight_data_test$hour <- as.factor(flight_data_test$hour)


```


```{r}

flights.dummy1 <- model.matrix(~hour, data=flight_data_test)
flights.dummy1 <- flights.dummy1[,-1]

```

#Join it together


```{r}
flight_data_test_all <- as.data.frame(cbind(flights.dummy, flights.dummy1))


flight_data_test_all$Weather <- flight_data_test$Weather
flight_data_test_all$FlightStatus <- flight_data_test$Flight.Status

```

#Split test and train

```{r}



train_index <- createDataPartition(flight_data_test_all$FlightStatus, p=0.6, list=FALSE)

training <- flight_data_test_all[ train_index, ]
testing <- flight_data_test_all[ -train_index, ]

mod_fit_one <- glm(FlightStatus ~ ., data=training, family="binomial")


summary(mod_fit_one) # estimates 
exp(coef(mod_fit_one)) # odds ratios


testing$prediction <- predict(mod_fit_one, newdata=testing, type="response") # predicted probabilities



testing$predict <- factor(ifelse(testing$prediction >= 0.52389118, "delayed", "ontime"))


#set positive class to ontime, and draw the confusion matrix 
confusionMatrix(data = testing$predict, reference = testing$FlightStatus, positive = levels(testing$FlightStatus)[1])
```






```{r}

pred <- prediction( testing$prediction, testing$FlightStatus, label.ordering = c("delayed", "ontime"))
perf <- performance(pred,"tpr","fpr")
plot(perf)
abline(a=0, b= 1)


#print out area under the curve

#perf <- performance(pred, "auc")
#print(perf@y.values[[1]])


cutoffs <- data.frame(cut=perf@alpha.values[[1]], fpr=perf@x.values[[1]], 
                      tpr=perf@y.values[[1]])



```

```{r}

#make the confusion matrix for train data


test$predict <- predict(model, type="response", newdata = test)

confusionMatrix(test$FlightStatus,if_else(test$predict > 0.5, "ontime", "delayed"))



pred <- prediction(  test$predict,  test$FlightStatus)
perf <- performance(pred,"tpr","fpr")
plot(perf)
abline(a=0, b= 1)

```

```{r}

FlightData_2017 <- read.csv("/Users/chrishilger/Downloads/Flight_Data/newfile.csv")
```

```{r}
FlightData_2017 <- FlightData_2017 %>% filter(YEAR != "YEAR")

```

```{r}
testing <- head(FlightData_2017)

```

```{r}

testing$DATE <- as.Date( paste(testing$MONTH , testing$DAY_OF_MONTH , testing$YEAR, sep = "-" )  , format = "%m-%d-%Y" )


testing1 <- testing %>%
  select(DATE, everything())

testing1 <- testing1[,-ncol(testing1)]


```

```{r}
#do it on the real data set

FlightData_2017_final <- FlightData_2017

FlightData_2017_final$DATE <- as.Date( paste(FlightData_2017_final$MONTH , FlightData_2017_final$DAY_OF_MONTH , FlightData_2017_final$YEAR, sep = "-" )  , format = "%m-%d-%Y" )


FlightData_2017_final <- FlightData_2017_final %>%
  select(DATE, everything())

FlightData_2017_final <- FlightData_2017_final[,-ncol(FlightData_2017_final)]

```

```{r}
FlightData_2017_final <- FlightData_2017_final %>% arrange(DATE)
```

```{r}
flightsDB <- FlightData_2017_final
```


```{r}
airportsDB <- read.csv('/Users/chrishilger/Downloads/Flight_Data/Lookup/L_AIRPORT_ID.csv',
                header = TRUE, stringsAsFactors = FALSE)
carriersDB <- read.csv('/Users/chrishilger/Downloads/Flight_Data/Lookup/L_UNIQUE_CARRIERS.csv',
                        header = TRUE, stringsAsFactors = FALSE)
```



```{r}
holidays <- c('2017-01-02', '2017-01-16', '2017-02-20', '2017-05-29',
            '2017-07-04', '2017-09-04', '2017-10-09', '2017-11-10',
            '2017-11-23', '2017-12-25') # Ten major holidays, including Memorial Day, Columbus Day, Labor Day, MLK Day
                                            # Veteran's Day, New Year's, President's Day, Independence Day, Thanksgiving, 
                                            # and Christmas Day.
holidayDates <- as.Date(holidays)
```


```{r}
#Find if date is holiday function

DaysToHoliday <- function(month, day){ # Input a month and day from the flightsDB
      
    # Get our year.
    year <- 2017
  
    # Paste on a 2013 for November and December dates.
    
    currDate <- as.Date(paste(year,month,day,sep = '-')) # Create a DATE object we can use to calculate the time difference
    
      
    numDays <- as.numeric(min(abs(currDate-holidayDates))) # Now find the minimum difference between the date and our holidays
    return(numDays)                                        # We can vectorize this to automatically find the minimum closest
                                                             # holiday by subtracting all holidays at once
      
}
```


```{r}
#hashing table for days to holiday

datesOfYear <- unique(flightsDB[,3:4]) # Get all of the dates through unique Month/Day combinations
datesOfYear$HDAYS <- mapply(DaysToHoliday, datesOfYear$MONTH, datesOfYear$DAY_OF_MONTH) 
    

```


```{r}
#read from our hashing table


InputDays <- function(month,day){
    finalDays <- datesOfYear$HDAYS[datesOfYear$MONTH == month & datesOfYear$DAY_OF_MONTH == day] # Find which row to get
    return(finalDays)
}
```

```{r}
#add the holidays feature to our table

flightsDB$HDAYS <- mapply(InputDays, flightsDB$MONTH, flightsDB$DAY_OF_MONTH)
```





```{r}
flightsDB$ARR_HOUR <- trunc(flightsDB$CRS_ARR_TIME/100) # Cuts off the minutes, essentially.
flightsDB$DEP_HOUR <- trunc(flightsDB$CRS_DEP_TIME/100)
```



```{r}
top_departuresDB <- flightsDB %>% 
  group_by(ORIGIN_AIRPORT_ID) %>%
  summarize(TOTAL_DEPARTING_FLIGHTS = n()) %>%
  arrange(desc(TOTAL_DEPARTING_FLIGHTS))


top_departuresDB <- head(top_departuresDB, 50)
```

```{r}
flightsDB_joined <- flightsDB_joined %>% 
  filter(ORIGIN_AIRPORT_ID %in% top_departuresDB$ORIGIN_AIRPORT_ID)
```

```{r}
flightsDB_joined <- flightsDB_joined %>% 
  filter(DEST_AIRPORT_ID %in% top_departuresDB$ORIGIN_AIRPORT_ID)
```

```{r}



```

```{r}



flightsDB_joined <- left_join(flightsDB_top_dep_dest, carriersDB, by = c("UNIQUE_CARRIER" ="Code"))

flightsDB_joined <- left_join(flightsDB_joined, airportsDB, by = c("ORIGIN_AIRPORT_ID" ="Code"))

flightsDB_joined <- left_join(flightsDB_joined, airportsDB, by = c("DEST_AIRPORT_ID" ="Code"))

flightsDB_joined <- rename(flightsDB_joined, CARRIER_NAME = 'Description.x' )
flightsDB_joined <- rename(flightsDB_joined, ORIGIN_AIRPORT = 'Description.y' )
flightsDB_joined <- rename(flightsDB_joined, DESTINATION_AIRPORT = 'Description' )



```

```{r}
test <- head(flightsDB_joined)

test <-test[,-1]
```


```{r}
flightsDB_joined$CARRIER_CODE <- as.numeric(as.factor(flightsDB_joined$UNIQUE_CARRIER))
```

```{r}


flightsDB_joined <-flightsDB_joined[,-1]
```

```{r}
write.csv(flightsDB_joined, 'FinalFlightsNumeric.csv')
```



#lookup type of plane from tail number
```{r}
tailDB <- read.csv("MASTER.txt")
```

```{r}
aircraftDB <- read.csv("ACFTREF.txt")
```

```{r}
aircraftDB <- aircraftDB %>% select(CODE, MFR , MODEL, NO.ENG, NO.SEATS)
```


```{r}
tailDB <- tailDB %>% select(N.NUMBER, YEAR.MFR, MFR.MDL.CODE)

tailDB$N.NUMBER <- paste("N",tailDB$N.NUMBER, sep ="")

```


```{r}
testDB <- left_join(flightsDB_joined, tailDB, by = c("TAIL_NUM" ="N.NUMBER"))
```


```{r}
testDB_narm <-testDB %>% 
  filter(!is.na(YEAR.MFR) & !is.na(MFR.MDL.CODE))
```



```{r}
flightsDB_joined_model <- left_join(testDB_narm, aircraftDB, by = c("MFR.MDL.CODE" ="CODE"))
```


```{r}
write.csv(flightsDB_joined_model, "FinalFlightsNumeric_with_Aircraft_Info.csv")
```




